import { Metadata } from "next";
import Link from "next/link"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next JS Tutorial - Codevolution",
    template: "%s | Codevolution"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
      <header>
        <h1 style={{
          backgroundColor: "yellow",
          display: "inline-block"
        }}>header</h1>
      

      </header>
      <Link href="/" style={{
        display: "inline-block",
        width: "1 rem"
      }}>Home</Link>
        {children}
        
        </body>
    </html>
  )
}
